apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-worker
  namespace: pv-lab-07
spec:
  containers:
    - name: main
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "temporary job output" > /workspace/result.txt
          sleep 3600
      volumeMounts:
        - name: workspace
          mountPath: /workspace

# This is useful when an application needs storage with CSI capabilities but does not need that storage to outlive the Pod.
  volumes:
    - name: workspace
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce

            resources:
              requests:
                storage: 1Gi
