apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delayed-data
  namespace: pv-lab-05
spec:
  storageClassName: pv-lab-delayed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
