apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  namespace: pv-lab-04
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
