apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: team-a-route
  namespace: team-a
spec:
  parentRefs:
    - name: ________
      namespace: ________
  hostnames:
    - team-a.shared.gateway.local
  rules:
    - backendRefs:
        - name: ________
          namespace: ________
          port: 8080
