apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-demo
  namespace: volumes-lab
spec:
  volumes:
    - name: ________
      ________:
        name: ________
        items:
          - key: ________
            path: ________
  containers:
    - name: reader
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          while true; do
            printf 'Current value: '
            cat /config/message.txt
            sleep 5
          done
      volumeMounts:
        - name: ________
          mountPath: ________
          readOnly: true
