apiVersion: v1
kind: Namespace
metadata:
  name: service-lab-final
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  namespace: service-lab-final
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
        - name: quote-api
          image: hashicorp/http-echo:1.0.0
          args:
            - "-listen=:8080"
            - "-text=stable-networking-for-ephemeral-pods"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: quote-api
  namespace: service-lab-final
spec:
  selector:
    app: quote-api
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: quote-api-headless
  namespace: service-lab-final
spec:
  clusterIP: None
  selector:
    app: quote-api
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: quote-api-public
  namespace: service-lab-final
spec:
  type: NodePort
  selector:
    app: quote-api
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
---
apiVersion: v1
kind: Pod
metadata:
  name: final-client
  namespace: service-lab-final
spec:
  containers:
    - name: client
      image: curlimages/curl:8.10.1
      command:
        - sh
        - -c
        - "echo Stable service DNS: quote-api; sleep 3600"
