apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-data
  namespace: volumes-lab
spec:
  accessModes:
  # ReadWriteOnce (RWO): read-write on one node
  # ReadOnlyMany (ROX): read-only on many nodes
  # ReadWriteMany (RWX): read-write on many nodes
  # ReadWriteOncePod (RWOP): read-write by exactly one Pod cluster-wide
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
