apiVersion: v1
kind: Pod
metadata:
  name: projected-volume-demo
  namespace: volumes-lab
  labels:
    application: volume-lab
    environment: local
spec:
  volumes:
    - name: context
      ________:
        sources:
          - configMap:
              name: ________
              items:
                - key: application-name
                  path: application-name
          - secret:
              name: ________
              items:
                - key: api-token
                  path: api-token
          - downwardAPI:
              items:
                - path: pod-name
                  fieldRef:
                    fieldPath: ________
                - path: namespace
                  fieldRef:
                    fieldPath: ________
                - path: labels
                  fieldRef:
                    fieldPath: ________
  containers:
    - name: reader
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          while true; do
            echo "Application: $(cat /context/application-name)"
            echo "Pod: $(cat /context/pod-name)"
            echo "Namespace: $(cat /context/namespace)"
            sleep 15
          done
      volumeMounts:
        - name: context
          mountPath: ________
          readOnly: true
