apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-routing
  namespace: ingress-lab
spec:
  ingressClassName: nginx
  rules:
    - host: ________
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: ________
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quote-api
                port:
                  number: 80
