apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lab-retain-pv
spec:
  capacity:
    storage: ________
  accessModes:
    - ReadWriteOnce
  storageClassName: pv-lab-static
  persistentVolumeReclaimPolicy: ________
  local:
    path: ________
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ________
