apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lab-retain-pv
spec:
  # size of the space to create
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteOnce

  storageClassName: pv-lab-static

  # With Retain, Kubernetes preserves the underlying storage after the PVC is deleted.
  persistentVolumeReclaimPolicy: Retain

  local:
    path: /data/pv-lab-retain
    
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              # name of your node
              values:
                - minikube
