apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-data
  namespace: pv-lab-06
spec:
  storageClassName: ________
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
