apiVersion: v1
kind: Secret
metadata:
  name: projected-secret
  namespace: volumes-lab
type: Opaque
stringData:
  # should never be committed in git
  api-token: BN677767****bnbnbmfiwoehfiowuehfie_test
