apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: pv-lab-02
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
