apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-demo
  namespace: volumes-lab
spec:
  securityContext:
    fsGroup: ________
  volumes:
    - name: credentials
      secret:
        secretName: ________
        defaultMode: ________
  containers:
    - name: reader
      image: busybox:1.36
      securityContext:
        runAsUser: ________
        runAsGroup: ________
        runAsNonRoot: true
      command:
        - sh
        - -c
        - |
          echo "username=$(cat /credentials/username)"
          echo "password file is readable"
          sleep 3600
      volumeMounts:
        - name: credentials
          mountPath: ________
          readOnly: ________
