apiVersion: v1
kind: Secret
metadata:
  name: application-credentials
  namespace: volumes-lab
type: Opaque
stringData:
  # should never be commited in git
  username: test_username
  password: test_password
