apiVersion: v1
kind: Service
metadata:
  name: counter
  namespace: pv-lab-08
spec:
  clusterIP: None
  selector:
    app: counter
  ports:
    - name: placeholder
      port: 80
      targetPort: 8080
