apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pv-lab-final
provisioner: k8s.io/minikube-hostpath 
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
