.PHONY: check cluster validate apply-all test-all cleanup delete-cluster

check:
	./scripts/check-prereqs.sh

cluster:
	./scripts/create-cluster.sh

validate:
	./scripts/validate-solutions.sh

apply-all:
	./scripts/apply-all-solutions.sh

test-all:
	./scripts/test-all-solutions.sh

cleanup:
	./scripts/cleanup-all.sh

delete-cluster:
	./scripts/delete-cluster.sh
